feat: add probes to helm chart
Lerentis/bitwarden-crd-operator pull request #36
Opened 2023-08-18 12:45 UTC by mbathe19

Hi @Lerentis,

adding the prob-values to the values file.

Regards,

Michel

2023-08-18 15:01 UTC, Lerentis requested changes
Hi @mbathe19 ,

Thanks for the PR. Can you bump the chart version and list the change there as well?

2023-08-21 09:37 UTC, mbathe19 commented
Hi @Lerentis,
added Changelog and bumped Chart Version.
Hopefully its now ok for you?

2023-08-21 09:43 UTC, Lerentis requested changes
just a minor change on the changelog kind and this is good to merge :)

2023-08-21 09:43 UTC, Lerentis commented on charts/bitwarden-crd-operator/Chart.yaml
> +    - kind: feat
```suggestion
    - kind: added
```
supported kinds are added, changed, deprecated, removed, fixed and security as stated here: https://artifacthub.io/docs/topics/annotations/helm/

2023-08-21 09:44 UTC, Lerentis approved these changes

2023-08-21 09:49 UTC, merged